name: Publish Mod

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          namespace: Fifty
          description: A server utility framework providing a robust chat commands api and much more 
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: Server_Utilities
          version: 2.4.3
          community: Northstar
          dev: false
          categories: Mods Server-side
          path: mods
